services:
  backend:
    image: ghcr.io/pttcodingman/just-wiki/backend:main
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file: .env
    restart: unless-stopped

  frontend:
    image: ghcr.io/pttcodingman/just-wiki/frontend:main
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
